### ISSUE TITLE
Category view doesn't work currently, in VS integration

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.PropertyEditing#213]
This worked a few days ago, with an older proppy, but now when changing Arrange by from Name to Category I see the error below in the debug output.  And proppy is blank, besides the Name/Category menu itself showing.

```
Exception thrown: 'System.NullReferenceException' in Xamarin.PropertyEditing.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
System.Windows.Data Error: 8 : Cannot save value from target back to source. BindingExpression:Path=IsChecked; DataItem='ArrangeModeViewModel' (HashCode=29579550); target element is 'MenuItem' (Name=''); target property is 'IsChecked' (type 'Boolean') NullReferenceException:'System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.PropertyEditing.ViewModels.PanelViewModel.OnAddEditors(IEnumerable`1 editors) in C:\myhome\xamarin\designer\external\Xamarin.PropertyEditing\Xamarin.PropertyEditing\ViewModels\PanelViewModel.cs:line 105
   at Xamarin.PropertyEditing.ViewModels.PanelViewModel.Arrange() in C:\myhome\xamarin\designer\external\Xamarin.PropertyEditing\Xamarin.PropertyEditing\ViewModels\PanelViewModel.cs:line 184
   at Xamarin.PropertyEditing.ViewModels.PanelViewModel.set_ArrangeMode(PropertyArrangeMode value) in C:\myhome\xamarin\designer\external\Xamarin.PropertyEditing\Xamarin.PropertyEditing\ViewModels\PanelViewModel.cs:line 53
   at Xamarin.PropertyEditing.ViewModels.ArrangeModeViewModel.set_IsChecked(Boolean value) in C:\myhome\xamarin\designer\external\Xamarin.PropertyEditing\Xamarin.PropertyEditing\ViewModels\ArrangeModeViewModel.cs:line 27'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='ArrangeMenuItem'```

**Comment by BretJohnson** [comment]
Update: The root cause here looks to be this line https://github.com/xamarin/Xamarin.PropertyEditing/blob/08514627e0f50a39dee46b4b6ee13a670302bf7f/Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs#L105, which generates an NRE if GroupedTypes isn't set on the platform. I just worked around that on the VS side, by always setting it to the empty dictionary & things now work OK.

So this bug isn't urgent, but ideally Proppy should change to either default `GroupedTypes` to the empty dictionary instead of null or handle a null `GroupedTypes` here and elsewhere.
